// エクセル「RecipeList」から読み取ったデータベース（全31種）
// ※料理名はエクセルの記載通り（ひらがな・長い名称もそのまま）にしています
const allRecipes = [
  { "name": "しんりょくアボカドグラタン", "category": "Curry", "baseEnergy": 24802, "bonus": 1.78, "ingredients": { "モーモーミルク": 41, "ほっこりポテト": 20, "ピュアなオイル": 32, "つやつやアボカド": 22 } },
  { "name": "いあいぎりすき焼きカレー", "category": "Curry", "baseEnergy": 20655, "bonus": 1.61, "ingredients": { "マメミート": 26, "ふといながねぎ": 27, "とくせんエッグ": 22, "あまいミツ": 26 } },
  { "name": "めざめるパワーシチュー", "category": "Curry", "baseEnergy": 19061, "bonus": 1.61, "ingredients": { "ワカクサ大豆": 28, "あんみんトマト": 25, "あじわいキノコ": 23, "めざましコーヒー": 16 } },
  { "name": "なりきりバケッチャシチュー", "category": "Curry", "baseEnergy": 15621, "bonus": 1.48, "ingredients": { "マメミート": 16, "ほっこりポテト": 18, "あじわいキノコ": 25, "ずっしりカボチャ": 10 } },
  { "name": "れんごくコーンキーマカレー", "category": "Curry", "baseEnergy": 13690, "bonus": 1.48, "ingredients": { "マメミート": 24, "げきからハーブ": 27, "ワカクサコーン": 14, "あったかジンジャー": 12 } },
  { "name": "ぜったいねむりバターカレー", "category": "Curry", "baseEnergy": 11556, "bonus": 1.35, "ingredients": { "モーモーミルク": 10, "ほっこりポテト": 18, "あんみんトマト": 15, "リラックスカカオ": 12 } },
  { "name": "あぶりテールカレー", "category": "Curry", "baseEnergy": 7483, "bonus": 1.25, "ingredients": { "げきからハーブ": 25, "おいしいシッポ": 8 } },
  { "name": "キノコのほうしカレー", "category": "Curry", "baseEnergy": 6430, "bonus": 1.21, "ingredients": { "あじわいキノコ": 14, "ほっこりポテト": 9 } },
  { "name": "おやこあいいりどうふカレー", "category": "Curry", "baseEnergy": 5832, "bonus": 1.21, "ingredients": { "ワカクサ大豆": 12, "マメミート": 6, "とくせんエッグ": 8, "ふといながねぎ": 9 } },
  { "name": "ビルドアップマメカレー", "category": "Curry", "baseEnergy": 5683, "bonus": 1.21, "ingredients": { "ワカクサ大豆": 12, "マメミート": 6, "げきからハーブ": 4, "とくせんエッグ": 4 } },
  { "name": "ニンジャカレー", "category": "Curry", "baseEnergy": 4943, "bonus": 1.21, "ingredients": { "ワカクサ大豆": 15, "マメミート": 9, "ふといながねぎ": 9, "あじわいキノコ": 5 } },
  { "name": "ソーラーパワー特製キーマカレー", "category": "Curry", "baseEnergy": 4488, "bonus": 1.17, "ingredients": { "あんみんトマト": 10, "げきからハーブ": 6, "マメミート": 10 } },
  { "name": "からくちネギもりカレー", "category": "Curry", "baseEnergy": 4436, "bonus": 1.17, "ingredients": { "ふといながねぎ": 14, "あったかジンジャー": 10, "げきからハーブ": 8 } },
  { "name": "ふくよかマメカレー", "category": "Curry", "baseEnergy": 3236, "bonus": 1.17, "ingredients": { "ワカクサ大豆": 12, "マメミート": 6, "とくせんエッグ": 4 } },
  { "name": "ほっこりホワイトシチュー", "category": "Curry", "baseEnergy": 3181, "bonus": 1.17, "ingredients": { "モーモーミルク": 10, "ほっこりポテト": 8, "あじわいキノコ": 4 } },
  { "name": "とけるオムカレー", "category": "Curry", "baseEnergy": 2150, "bonus": 1.11, "ingredients": { "とくせんエッグ": 10, "あんみんトマト": 6 } },
  { "name": "サンパワートマトカレー", "category": "Curry", "baseEnergy": 2078, "bonus": 1.11, "ingredients": { "げきからハーブ": 5, "あんみんトマト": 10 } },
  { "name": "ひでりカツレツカレー", "category": "Curry", "baseEnergy": 1942, "bonus": 1.11, "ingredients": { "マメミート": 10, "ピュアなオイル": 5 } },
  { "name": "満腹チーズバーグカレー", "category": "Curry", "baseEnergy": 1910, "bonus": 1.11, "ingredients": { "モーモーミルク": 8, "マメミート": 8 } },
  { "name": "マメバーグカレー", "category": "Curry", "baseEnergy": 856, "bonus": 1.06, "ingredients": { "マメミート": 7 } },
  { "name": "ベイビィハニーカレー", "category": "Curry", "baseEnergy": 839, "bonus": 1.06, "ingredients": { "あまいミツ": 7 } },
  { "name": "たんじゅんホワイトシチュー", "category": "Curry", "baseEnergy": 814, "bonus": 1.06, "ingredients": { "モーモーミルク": 7 } },
  { "name": "とくせんリンゴカレー", "category": "Curry", "baseEnergy": 748, "bonus": 1.06, "ingredients": { "とくせんリンゴ": 7 } },
  { "name": "じならしワカモレチップス", "category": "Salad", "baseEnergy": 25162, "bonus": 1.78, "ingredients": { "ワカクサ大豆": 22, "げきからハーブ": 30, "ワカクサコーン": 25, "つやつやアボカド": 28 } },
  { "name": "まけんきコーヒーサラダ", "category": "Salad", "baseEnergy": 20218, "bonus": 1.61, "ingredients": { "マメミート": 28, "ほっこりポテト": 22, "ピュアなオイル": 22, "めざましコーヒー": 28 } },
  { "name": "りんごさんヨーグルトサラダ", "category": "Salad", "baseEnergy": 19293, "bonus": 1.61, "ingredients": { "モーモーミルク": 18, "とくせんリンゴ": 28, "とくせんエッグ": 35, "あんみんトマト": 23 } },
  { "name": "はなふぶきミモザサラダ", "category": "Salad", "baseEnergy": 11811, "bonus": 1.35, "ingredients": { "マメミート": 12, "ほっこりポテト": 15, "ピュアなオイル": 17, "とくせんエッグ": 25 } },
  { "name": "ドキドキこわいかおパンケーキ", "category": "Dessert", "baseEnergy": 24354, "bonus": 1.78, "ingredients": { "とくせんエッグ": 24, "あんみんトマト": 29, "あまいミツ": 32, "ずっしりカボチャ":
